### ISSUE TITLE
Arguments

### ISSUE THREAD

**Issue by simonbusborg** [madeingnecca/sublime-fillerati#1]
Would it be possible that you add the arguments available for this package? As well as the most common commands? 

Maybe it is possible to do a fillerati:mobydick:300 ?

**Comment by madeingnecca** [comment]
The only command available is "fillerati", which fetches 300 characters from a random book. If you want to fetch a different count of characters you just have to type, for example, 1000, select it and launch fillerati from the command palette and this will fetch 1000 characters. It supports multiple selections, so you can have selections each with a different number of chars to fetch.
At the the moment there is no way to specify the book, but it could be a future implementation.

**Comment by madeingnecca** [comment]
The only argument available is the number of characters to fetch, which defaults to 300. The idea is to add the book as a second argument in a future implementation. In this way you can write your custom sublime-commands file, calling the command fillerati with the desidered values for the arguments.

**Comment by madeingnecca** [comment]
I've added the book parameter in the last commit.
You can write your custom fillerati command, for example:
<code>
{ "caption": "Fillerati Mobydick", "command": "fillerati", "args": {"n": 300, "b": "mbydck"} }
</code>
For the list of the books have a look at Fillerati.sublime-settings file.
