### ISSUE TITLE
Package control

### ISSUE THREAD

**Issue by cardern** [madeingnecca/sublime-fillerati#2]
It would be pretty cool if this was included in package control. Would you be interested in pursuing this, or if not opposed if I forked the repo and gave it a try?

**Comment by madeingnecca** [comment]
Hi
Go ahead and fork it.
The plugin is not ST3 ready and it was one of my first python projects, so the code may not be the best to maintain.
Have fun!

**Comment by cardern** [comment]
OK thank you!
